### PR TITLE
Screen page actions and feedback

### PR DESCRIPTION
**Pull request by justingiffard**

### CODE REVIEW

**Comment by Julusian** [comment]
@justingiffard you have been doing some good work here recently, and have more time/motivation than me to do things for this module so I've added you as a collaborator.
Feel free to push changes directly to master from now on :)
If you want a second pair of eyes on anything, you are welcome to tag me in things.
When you are happy, do a commit like this https://github.com/bitfocus/companion-module-behringer-x32/commit/b64ec6de891ffbdc4c42492f1afeb952af985555 to update the version number and changelog and post a message in the module-development slack to get it included in core

**Comment by jsnyder886** [comment]
+1 from me on this for the list of kudos for the great work!  Thanks Justin!

**Comment by justingiffard** [comment]
> @justingiffard you have been doing some good work here recently, and have more time/motivation than me to do things for this module so I've added you as a collaborator. Feel free to push changes directly to master from now on :) If you want a second pair of eyes on anything, you are welcome to tag me in things. When you are happy, do a commit like this [b64ec6d](https://github.com/bitfocus/companion-module-behringer-x32/commit/b64ec6de891ffbdc4c42492f1afeb952af985555) to update the version number and changelog and post a message in the module-development slack to get it included in core

Oh wow thank you so very much. I am honoured. I will look into these PRs now to deal with the merge conflicts 😊

**Comment by justingiffard** [comment]
> When you are happy, do a commit like this [b64ec6d](https://github.com/bitfocus/companion-module-behringer-x32/commit/b64ec6de891ffbdc4c42492f1afeb952af985555) to update the version number and changelog and post a message in the module-development slack to get it included in core

Hi @Julusian, not doing it just yet (will do after I test a branch tomorrow and merge that) but what is the convention for version number? Would next version be 2.9.0 and if it was a bugfix it would be 2.8.1?
Also what do I say on slack? Just that there is a new version of companion-module-behringer-x32 and ask them to build it?

**Pull request merged**
